# Generated by Django 3.0.2 on 2021-04-11 05:05

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.IntegerField(null=True)),
                ('surname', models.TextField(default='', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Category/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='alemsite.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alemsite.Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='Products/%Y/%m/%d')),
                ('photo1', models.ImageField(blank=True, upload_to='Photo1/%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='Photo2/%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='Photo3/%Y/%m/%d')),
                ('photo4', models.ImageField(blank=True, upload_to='Photo4/%Y/%m/%d')),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Color')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Gender')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.New')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Size')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Status')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alemsite.Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('inprocess', models.BooleanField(default=False)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productss', to='alemsite.Category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productss', to='alemsite.Color')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productss', to='alemsite.Products')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productss', to='alemsite.Size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai+', to='alemsite.Category')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alemsite.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alemsite.Category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alemsite.Color')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alemsite.Gender')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alemsite.Products')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alemsite.Size')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alemsite.Status')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alemsite.Subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
